name: AllChecks
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35

      - name: Check changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "Checking file: $file"
            ./gradlew onChainCheck -PfileToCheck=$file --info --stacktrace || {
              echo "Failed to check $file"
              exit 1
            }
          done
  
      - name: Build
        run: |
          echo "Running full build..."
          ./gradlew run --info --stacktrace
